import Foundation

/// Les 100 messages du matin. Un par jour, dans l'ordre, puis ça reboucle.
/// Pour en ajouter ou en retirer : édite la liste et relance ./build.sh —
/// la rotation s'adapte toute seule au nombre de lignes.
enum Quotes {

    static let all: [String] = [
        "Debout, glow up, au travail.",
        "Talons hauts, zéro excuse.",
        "Café, gloss, et go.",
        "Boss mood dès 8 h.",
        "Mains manucurées, agenda brutal.",
        "Travaille comme une icône.",
        "Glow up d'abord, to-do ensuite.",
        "Jolie, ponctuelle, redoutable.",
        "Le lit est fait. À toi de jouer.",
        "Mascara posé, mode focus activé.",
        "Sois le plan A.",
        "Lève-toi, ton empire t'attend.",
        "Parfum, playlist, puissance.",
        "On ne slay pas en snoozant.",
        "Deadline glamour, résultat brutal.",
        "Ferme Instagram, ouvre le laptop.",
        "Douce le matin, impitoyable à midi.",
        "Ton lipstick est prêt. Et toi ?",
        "Bosse maintenant, brille ce soir.",
        "Girl boss, pas girl stress.",
        "Un café, puis on domine.",
        "La meilleure de la pièce, en silence.",
        "Pas de soft launch aujourd'hui.",
        "Talons, thé, discipline.",
        "Fais-le jolie, fais-le vite.",
        "Le glow vient du travail fini.",
        "Réveille-toi, tu as un empire.",
        "Sexy, mais avec un planning.",
        "Moins de scroll, plus de slay.",
        "Ta to-do a peur de toi.",
        "Bosse jusqu'à ce que ça brille.",
        "Chignon serré, objectifs clairs.",
        "Aujourd'hui : mode diva efficace.",
        "Ni pressée, ni en retard. Prête.",
        "Fais de l'argent, fais du style.",
        "Le monde peut attendre. Pas ta to-do.",
        "Glow, grind, glow again.",
        "Pas de jour off pour l'ambition.",
        "Beauté prête, cerveau allumé.",
        "Range le téléphone. Prends le stylo.",
        "Soft life, hard work.",
        "Mets du rouge et termine-le.",
        "Lève-toi. Personne ne le fera.",
        "Jolie ET compétente. Toujours ET.",
        "Ton alarme n'était pas une suggestion.",
        "Slay d'abord, scroll après.",
        "Travaille comme si on filmait.",
        "Main character, mais avec un planning.",
        "Fais-toi belle pour toi, puis bosse.",
        "Le glow up commence à 7 h.",
        "Objectif : insupportablement efficace.",
        "Cheveux impeccables, boîte mail vide.",
        "Gloss appliqué. Mission acceptée.",
        "Pas de drama avant le déjeuner.",
        "Sois la femme que tu suis en ligne.",
        "Lève-toi et sois inoubliable.",
        "Ton empire ne se construit pas seul.",
        "Talons dans l'ascenseur, plan en tête.",
        "Élégante dehors, machine dedans.",
        "Fais briller le travail, pas juste toi.",
        "Aujourd'hui on livre, pas on réfléchit.",
        "Sois chic et hors d'atteinte.",
        "Boss girl, pas busy girl.",
        "Playlist forte, ambitions plus fortes.",
        "La beauté ouvre, le travail garde.",
        "Debout, reine. Il est l'heure.",
        "Finis-le avant le deuxième café.",
        "Ne sois pas mignonne. Sois dangereuse.",
        "Manucure fraîche, mails envoyés.",
        "Le glow se mérite avant midi.",
        "Sois rapide, sois jolie, sois payée.",
        "Aucune excuse ne porte du gloss.",
        "Ton lundi ne te fait pas peur.",
        "Bosse fort, brille encore plus fort.",
        "Soirée méritée, journée gagnée.",
        "Girl, get up. Get it done.",
        "Le silence du matin est à toi.",
        "Fais ton lit, fais ton chiffre.",
        "Icône le jour, machine la nuit.",
        "Prépare-toi comme si tu allais gagner.",
        "Charme réglé, agenda verrouillé.",
        "Slay the day, pas ton énergie.",
        "Robe simple, résultats spectaculaires.",
        "Commence moche, finis iconique.",
        "Ton futur toi te regarde. Souris.",
        "Moins de perfection, plus de terminé.",
        "Sois sexy à force d'être sérieuse.",
        "Réveille-toi et sois la référence.",
        "Discipline en soie.",
        "Fais du bruit en talons.",
        "La meilleure vengeance : un planning tenu.",
        "Bosse pour la version Pinterest de toi.",
        "Rouge à lèvres, deadline, victoire.",
        "Rien de doux avant que ce soit fini.",
        "Aujourd'hui, sois insupportablement bonne.",
        "Glow up, then show up.",
        "Sois la raison pour laquelle ils bossent.",
        "Café noir, décisions nettes.",
        "Debout : le monde ne s'excusera pas.",
        "Termine-le, puis mets la robe."
    ]

    /// Le message du jour. Calculé sur la date locale : il ne change pas si tu
    /// relances le widget ou redémarres le Mac, et bascule à minuit.
    static func today(_ now: Date = Date()) -> String {
        guard !all.isEmpty else { return "" }
        let day = Calendar.current.ordinality(of: .day, in: .era, for: now) ?? 0
        return all[((day % all.count) + all.count) % all.count]
    }
}
